#**1. Set up environment**

##1.1 Clone github repository

In [159]:
!git clone https://github.com/kkartsen/NLP_Hidden-Gems_Final-Project.git

Cloning into 'NLP_Hidden-Gems_Final-Project'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (12/12), 46.25 MiB | 16.57 MiB/s, done.
Resolving deltas: 100% (2/2), done.

##1.2 Imports

In [160]:
%cd NLP_Hidden-Gems_Final-Project

import pandas as pd
import os
import re
import numpy as np
import json
import tqdm
import warnings
import zipfile
import glob
import matplotlib.pyplot as plt
warnings.filterwarnings("ignore")

/content/NLP_Hidden-Gems_Final-Project/NLP_Hidden-Gems_Final-Project/NLP_Hidden-Gems_Final-Project

##1.3 Access data

Extract training data

In [161]:
# extract training data
output_filename = "train.txt.zip"
parts = ["train.txt.zip.001", "train.txt.zip.002"]

with open(output_filename, "wb") as outfile:
    for part in parts:
        with open(part, "rb") as infile:
            outfile.write(infile.read())
print(f"Merged {len(parts)} parts into {output_filename}")

with zipfile.ZipFile("train.txt.zip", "r") as zip_ref:
    zip_ref.extractall()

Merged 2 parts into train.txt.zip

Load data

In [162]:
train_file_path = os.path.join(os.getcwd(), 'train.txt')
val_file_path = os.path.join(os.getcwd(), 'val.txt')
test_file_path = os.path.join(os.getcwd(), 'test.txt')

with open(val_file_path, encoding='utf-8') as f:
    val_json_data = json.load(f)
with open(train_file_path, encoding='utf-8') as f:
    train_json_data = json.load(f)
with open(test_file_path, encoding='utf-8') as f:
    test_json_data = json.load(f)

#**2. Analyze & Clean Data**

##2.1 Analyze and clean training data

In [195]:
print('Total length of the dataset: ')
print('Train: {}\nValidate: {}\nTest: {}'.format(len(train_json_data), len(val_json_data), len(test_json_data)))

Total length of the dataset:
Train: 42000
Validate: 9000
Test: 9000

In [196]:
train_ds = pd.read_json(train_file_path)
train_ds.shape

(42000, 11)

In [197]:
train_ds.head()

,publication_ID,Citations,pubDate,language,title,journal,abstract,keywords,authors,venue,doi
0,17396995,17957262;21818356;24164861;21818356;24164861;2...,2007 May 1,eng,Herpes simplex virus type 2 infection does not...,The Journal of infectious diseases,We sought to compare baseline and longitudinal...,Adult;California;epidemiology;Cohort Studies;H...,"[{'name': 'Edward R Cachay', 'org': 'Universit...",{'name': 'The Journal of infectious diseases'},10.1086/513568
1,16779733,19197361;19399183;20041174;20300572;17311474;2...,2006 Jul 15,eng,Efficacy of the anti Candida rAls3p N or rAls1...,The Journal of infectious diseases.,We have shown that vaccination with the recomb...,Animals;Candida;immunology;isolation & purific...,"[{'name': 'Brad J Spellberg', 'org': 'Departme...",{'name': 'The Journal of infectious diseases'},10.1086/504691
2,12412787,28740334,2002 Nov,eng,Role of the interleukin 6 interleukin 6 solubl...,Journal of bone and mineral research : the off...,We have observed a strong correlation between ...,Adult;Animals;Bone Resorption;metabolism;Bone ...,"[{'name': 'Karl Insogna', 'org': 'Department o...",{'name': 'Journal of bone and mineral research...,0
3,18070707,22567368;22348393;22495885;23874387;23100393;2...,2007 Dec,eng,Genetic events in the pathogenesis of multiple...,Best practice & research. Clinical haematology,The genetics of myeloma has been increasingly ...,Gene Expression Profiling;Humans;Immunoglobuli...,"[{'name': 'W.J. Chng', 'org': 'Mayo Clinic Ari...",{'name': 'Best practice & research. Clinical h...,10.1016/j.beha.2007.08.004
4,16365419,20498830;26334995,2006 Jan 01,eng,PU 1 regulates cathepsin S expression in profe...,"Journal of immunology (Baltimore, Md. : 1950)",Cathepsin S (CTSS) is a cysteine protease that...,Animals;Antigen-Presenting Cells;immunology;me...,"[{'name': 'Ying Wang', 'id': '53f5626bdabfae5d...","{'name': 'Journal of immunology (Baltimore, Md...",10.4049/jimmunol.176.1.275

Note no NaN values but prev code shows us they are represented with 0 instead

Also all columns are objects (strings?) except for one- publication_ID

In [198]:
train_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   publication_ID  42000 non-null  int64
 1   Citations       42000 non-null  object
 2   pubDate         42000 non-null  object
 3   language        42000 non-null  object
 4   title           42000 non-null  object
 5   journal         42000 non-null  object
 6   abstract        42000 non-null  object
 7   keywords        42000 non-null  object
 8   authors         42000 non-null  object
 9   venue           42000 non-null  object
 10  doi             42000 non-null  object
dtypes: int64(1), object(10)
memory usage: 3.5+ MB

Find how many values in each column are null (0):

Citations: 169, Abstract: 1074, Keywords: 2165, Venue: 3, DOI: 2231

In [199]:
zero_per_col = []

zero_per_col.append((train_ds['publication_ID'] == 0).sum().item())
zero_per_col.append((train_ds['Citations'] == 0).sum().item())
zero_per_col.append((train_ds['pubDate'] == 0).sum().item())
zero_per_col.append((train_ds['language'] == 0).sum().item())
zero_per_col.append((train_ds['title'] == 0).sum().item())
zero_per_col.append((train_ds['journal'] == 0).sum().item())
zero_per_col.append((train_ds['abstract'] == 0).sum().item())
zero_per_col.append((train_ds['keywords'] == 0).sum().item())
zero_per_col.append((train_ds['authors'] == 0).sum().item())
zero_per_col.append((train_ds['venue'] == '0').sum().item())
zero_per_col.append((train_ds['doi'] == '0').sum().item())

print(zero_per_col)

[0, 169, 0, 0, 0, 0, 1074, 2165, 0, 3, 2231]

Data must include citations-- remove all rows where Citations has 0 data

Also remove all rows where any other column has 0 data to make dataset size slightly more manageable (42000 -> 37632 rows)

In [200]:
train_ds = train_ds[train_ds['Citations'] != 0]
train_ds = train_ds[train_ds['abstract'] != 0]
train_ds = train_ds[train_ds['keywords'] != 0]
train_ds = train_ds[train_ds['venue'] != '0']
train_ds = train_ds[train_ds['doi'] != '0']

#reset index
train_ds.reset_index(drop=True, inplace=True)

train_ds.shape

(37632, 11)

**Reformat citations column:**

*   Convert string to array
*   Remove NaN values in array
*   Calucate number of citations per row & add to new column
*   Remove rows with no citations

In [201]:
#Citations column is currently a string (ex: '17957262;21818356;24164861;21818356;24164861;28586396;28688377')
citations = []
num_citations = []

for i in range(len(train_ds)):
  c = train_ds['Citations'][i].split(';')
  for x in c:
    if x.lower() == 'nan':
      c.remove(x)
    else:
      x = int(x)
  citations.append(c)
  n = len(c)
  num_citations.append(n)

train_ds['Citations'] = citations
train_ds['num_citations'] = num_citations
train_ds = train_ds[train_ds['num_citations'] != 0]
train_ds.head()

,publication_ID,Citations,pubDate,language,title,journal,abstract,keywords,authors,venue,doi,num_citations
0,17396995,"[17957262, 21818356, 24164861, 21818356, 24164...",2007 May 1,eng,Herpes simplex virus type 2 infection does not...,The Journal of infectious diseases,We sought to compare baseline and longitudinal...,Adult;California;epidemiology;Cohort Studies;H...,"[{'name': 'Edward R Cachay', 'org': 'Universit...",{'name': 'The Journal of infectious diseases'},10.1086/513568,7
1,16779733,"[19197361, 19399183, 20041174, 20300572, 17311...",2006 Jul 15,eng,Efficacy of the anti Candida rAls3p N or rAls1...,The Journal of infectious diseases.,We have shown that vaccination with the recomb...,Animals;Candida;immunology;isolation & purific...,"[{'name': 'Brad J Spellberg', 'org': 'Departme...",{'name': 'The Journal of infectious diseases'},10.1086/504691,21
2,18070707,"[22567368, 22348393, 22495885, 23874387, 23100...",2007 Dec,eng,Genetic events in the pathogenesis of multiple...,Best practice & research. Clinical haematology,The genetics of myeloma has been increasingly ...,Gene Expression Profiling;Humans;Immunoglobuli...,"[{'name': 'W.J. Chng', 'org': 'Mayo Clinic Ari...",{'name': 'Best practice & research. Clinical h...,10.1016/j.beha.2007.08.004,18
3,16365419,"[20498830, 26334995]",2006 Jan 01,eng,PU 1 regulates cathepsin S expression in profe...,"Journal of immunology (Baltimore, Md. : 1950)",Cathepsin S (CTSS) is a cysteine protease that...,Animals;Antigen-Presenting Cells;immunology;me...,"[{'name': 'Ying Wang', 'id': '53f5626bdabfae5d...","{'name': 'Journal of immunology (Baltimore, Md...",10.4049/jimmunol.176.1.275,2
4,17251694,"[25793766, 26843986, 26977594, 31150452]",2007 Feb,ENG,Falls and gait characteristics among older per...,American journal of physical medicine & rehabi...,To prospectively determine the frequency and c...,Accidental Falls;Age Factors;Aged;Biomechanica...,"[{'name': 'Trina K. DeMott', 'org': 'Departmen...",{'name': 'American journal of physical medicin...,10.1097/PHM.0b013e31802ee1d1,4

**Reformat pubDate column:**

*   Convert string to datetime object
*   All format errors are due to hyphens-> resolve to later day/month/year

In [202]:
tester = []
errors = []

for i in range(len(train_ds)):
  try:
    tester.append(pd.to_datetime(train_ds['pubDate'][i], format='mixed'))
  except:
    #reformat [YYYY "Mon1"-"Mon2"] and [YYYY "Mon" DD1-DD2] to [YYYY "Mon2"] or [YYYY "Mon" DD2]
    end_index = train_ds['pubDate'][i].find("-")
    start_index = end_index - 1
    found = False
    while start_index >= 0 and not found:
      if train_ds['pubDate'][i][start_index] == " ":
        found = True
      else:
        start_index -= 1
    if found:
      reformat = train_ds['pubDate'][i][:start_index+1] + train_ds['pubDate'][i][end_index+1:]
      try:
        tester.append(pd.to_datetime(reformat, format='mixed'))
      except:
        #reformat [YYYY "Mon1" DD1-"Mon2" DD2] to [YYYY "Mon2" DD2]
        end_index = start_index
        start_index = end_index - 1
        found = False
        while start_index >= 0 and not found:
          if train_ds['pubDate'][i][start_index] == " ":
            found = True
          else:
            start_index -= 1
        reformat = reformat[:start_index+1] + reformat[end_index+1:]
        try:
          tester.append(pd.to_datetime(reformat, format='mixed'))
        except:
          errors.append(i)
          print("Original: ", train_ds['pubDate'][i], "\tReformatted: ", reformat)
    else:
      errors.append(i)
      print("Reformat Failed-- Original: ", train_ds['pubDate'][i])

print(len(errors), " errors total")
train_ds['pubDate'] = tester

0  errors total

In [203]:
train_ds.head()

,publication_ID,Citations,pubDate,language,title,journal,abstract,keywords,authors,venue,doi,num_citations
0,17396995,"[17957262, 21818356, 24164861, 21818356, 24164...",2007-05-01,eng,Herpes simplex virus type 2 infection does not...,The Journal of infectious diseases,We sought to compare baseline and longitudinal...,Adult;California;epidemiology;Cohort Studies;H...,"[{'name': 'Edward R Cachay', 'org': 'Universit...",{'name': 'The Journal of infectious diseases'},10.1086/513568,7
1,16779733,"[19197361, 19399183, 20041174, 20300572, 17311...",2006-07-15,eng,Efficacy of the anti Candida rAls3p N or rAls1...,The Journal of infectious diseases.,We have shown that vaccination with the recomb...,Animals;Candida;immunology;isolation & purific...,"[{'name': 'Brad J Spellberg', 'org': 'Departme...",{'name': 'The Journal of infectious diseases'},10.1086/504691,21
2,18070707,"[22567368, 22348393, 22495885, 23874387, 23100...",2007-12-01,eng,Genetic events in the pathogenesis of multiple...,Best practice & research. Clinical haematology,The genetics of myeloma has been increasingly ...,Gene Expression Profiling;Humans;Immunoglobuli...,"[{'name': 'W.J. Chng', 'org': 'Mayo Clinic Ari...",{'name': 'Best practice & research. Clinical h...,10.1016/j.beha.2007.08.004,18
3,16365419,"[20498830, 26334995]",2006-01-01,eng,PU 1 regulates cathepsin S expression in profe...,"Journal of immunology (Baltimore, Md. : 1950)",Cathepsin S (CTSS) is a cysteine protease that...,Animals;Antigen-Presenting Cells;immunology;me...,"[{'name': 'Ying Wang', 'id': '53f5626bdabfae5d...","{'name': 'Journal of immunology (Baltimore, Md...",10.4049/jimmunol.176.1.275,2
4,17251694,"[25793766, 26843986, 26977594, 31150452]",2007-02-01,ENG,Falls and gait characteristics among older per...,American journal of physical medicine & rehabi...,To prospectively determine the frequency and c...,Accidental Falls;Age Factors;Aged;Biomechanica...,"[{'name': 'Trina K. DeMott', 'org': 'Departmen...",{'name': 'American journal of physical medicin...,10.1097/PHM.0b013e31802ee1d1,4

Drop duplicates based on publicationID

In [204]:
train_ds = train_ds.drop_duplicates(subset=['publication_ID'])

In [205]:
train_ds.head()

,publication_ID,Citations,pubDate,language,title,journal,abstract,keywords,authors,venue,doi,num_citations
0,17396995,"[17957262, 21818356, 24164861, 21818356, 24164...",2007-05-01,eng,Herpes simplex virus type 2 infection does not...,The Journal of infectious diseases,We sought to compare baseline and longitudinal...,Adult;California;epidemiology;Cohort Studies;H...,"[{'name': 'Edward R Cachay', 'org': 'Universit...",{'name': 'The Journal of infectious diseases'},10.1086/513568,7
1,16779733,"[19197361, 19399183, 20041174, 20300572, 17311...",2006-07-15,eng,Efficacy of the anti Candida rAls3p N or rAls1...,The Journal of infectious diseases.,We have shown that vaccination with the recomb...,Animals;Candida;immunology;isolation & purific...,"[{'name': 'Brad J Spellberg', 'org': 'Departme...",{'name': 'The Journal of infectious diseases'},10.1086/504691,21
2,18070707,"[22567368, 22348393, 22495885, 23874387, 23100...",2007-12-01,eng,Genetic events in the pathogenesis of multiple...,Best practice & research. Clinical haematology,The genetics of myeloma has been increasingly ...,Gene Expression Profiling;Humans;Immunoglobuli...,"[{'name': 'W.J. Chng', 'org': 'Mayo Clinic Ari...",{'name': 'Best practice & research. Clinical h...,10.1016/j.beha.2007.08.004,18
3,16365419,"[20498830, 26334995]",2006-01-01,eng,PU 1 regulates cathepsin S expression in profe...,"Journal of immunology (Baltimore, Md. : 1950)",Cathepsin S (CTSS) is a cysteine protease that...,Animals;Antigen-Presenting Cells;immunology;me...,"[{'name': 'Ying Wang', 'id': '53f5626bdabfae5d...","{'name': 'Journal of immunology (Baltimore, Md...",10.4049/jimmunol.176.1.275,2
4,17251694,"[25793766, 26843986, 26977594, 31150452]",2007-02-01,ENG,Falls and gait characteristics among older per...,American journal of physical medicine & rehabi...,To prospectively determine the frequency and c...,Accidental Falls;Age Factors;Aged;Biomechanica...,"[{'name': 'Trina K. DeMott', 'org': 'Departmen...",{'name': 'American journal of physical medicin...,10.1097/PHM.0b013e31802ee1d1,4

In [206]:
train_ds.reset_index(drop=True, inplace=True)

**Reformat language column**


*   Remove non-english papers (two, both french)
*   Drop language column

In [207]:
train_ds['language'].unique()
train_ds['language'].value_counts()

language
eng    31304
ENG     5519
fre        2
Name: count, dtype: int64

In [208]:
train_ds = train_ds[train_ds['language'] != 'fre']

train_ds.drop(['language'], axis=1, inplace=True)

train_ds.reset_index(drop=True, inplace=True)

train_ds.head()

,publication_ID,Citations,pubDate,title,journal,abstract,keywords,authors,venue,doi,num_citations
0,17396995,"[17957262, 21818356, 24164861, 21818356, 24164...",2007-05-01,Herpes simplex virus type 2 infection does not...,The Journal of infectious diseases,We sought to compare baseline and longitudinal...,Adult;California;epidemiology;Cohort Studies;H...,"[{'name': 'Edward R Cachay', 'org': 'Universit...",{'name': 'The Journal of infectious diseases'},10.1086/513568,7
1,16779733,"[19197361, 19399183, 20041174, 20300572, 17311...",2006-07-15,Efficacy of the anti Candida rAls3p N or rAls1...,The Journal of infectious diseases.,We have shown that vaccination with the recomb...,Animals;Candida;immunology;isolation & purific...,"[{'name': 'Brad J Spellberg', 'org': 'Departme...",{'name': 'The Journal of infectious diseases'},10.1086/504691,21
2,18070707,"[22567368, 22348393, 22495885, 23874387, 23100...",2007-12-01,Genetic events in the pathogenesis of multiple...,Best practice & research. Clinical haematology,The genetics of myeloma has been increasingly ...,Gene Expression Profiling;Humans;Immunoglobuli...,"[{'name': 'W.J. Chng', 'org': 'Mayo Clinic Ari...",{'name': 'Best practice & research. Clinical h...,10.1016/j.beha.2007.08.004,18
3,16365419,"[20498830, 26334995]",2006-01-01,PU 1 regulates cathepsin S expression in profe...,"Journal of immunology (Baltimore, Md. : 1950)",Cathepsin S (CTSS) is a cysteine protease that...,Animals;Antigen-Presenting Cells;immunology;me...,"[{'name': 'Ying Wang', 'id': '53f5626bdabfae5d...","{'name': 'Journal of immunology (Baltimore, Md...",10.4049/jimmunol.176.1.275,2
4,17251694,"[25793766, 26843986, 26977594, 31150452]",2007-02-01,Falls and gait characteristics among older per...,American journal of physical medicine & rehabi...,To prospectively determine the frequency and c...,Accidental Falls;Age Factors;Aged;Biomechanica...,"[{'name': 'Trina K. DeMott', 'org': 'Departmen...",{'name': 'American journal of physical medicin...,10.1097/PHM.0b013e31802ee1d1,4

**Reformat keywords column:**

*   Convert string to array

In [209]:
print(train_ds['keywords'][0])

Adult;California;epidemiology;Cohort Studies;HIV Infections;blood;complications;epidemiology;virology;HIV-1;pathogenicity;Herpes Simplex;blood;complications;epidemiology;virology;Herpesvirus 2, Human;pathogenicity;Humans;Longitudinal Studies;Male;Prevalence;Retrospective Studies;Viral Load

In [210]:
#Keywords column is currently a string (ex: 'Adult;California;epidemiology;Cohort Studies;HIV Infections;blood;complications;epidemiology;virology;HIV-1;pathogenicity;Herpes Simplex;blood;complications;epidemiology;virology;Herpesvirus 2, Human;pathogenicity;Humans;Longitudinal Studies;Male;Prevalence;Retrospective Studies;Viral Load')
keywords = []

for i in range(len(train_ds)):
  k = train_ds['keywords'][i].split(';')
  for x in k:
    if x.lower() == 'nan':
      k.remove(x)
  keywords.append(k)

train_ds['keywords'] = keywords
train_ds.head()

,publication_ID,Citations,pubDate,title,journal,abstract,keywords,authors,venue,doi,num_citations
0,17396995,"[17957262, 21818356, 24164861, 21818356, 24164...",2007-05-01,Herpes simplex virus type 2 infection does not...,The Journal of infectious diseases,We sought to compare baseline and longitudinal...,"[Adult, California, epidemiology, Cohort Studi...","[{'name': 'Edward R Cachay', 'org': 'Universit...",{'name': 'The Journal of infectious diseases'},10.1086/513568,7
1,16779733,"[19197361, 19399183, 20041174, 20300572, 17311...",2006-07-15,Efficacy of the anti Candida rAls3p N or rAls1...,The Journal of infectious diseases.,We have shown that vaccination with the recomb...,"[Animals, Candida, immunology, isolation & pur...","[{'name': 'Brad J Spellberg', 'org': 'Departme...",{'name': 'The Journal of infectious diseases'},10.1086/504691,21
2,18070707,"[22567368, 22348393, 22495885, 23874387, 23100...",2007-12-01,Genetic events in the pathogenesis of multiple...,Best practice & research. Clinical haematology,The genetics of myeloma has been increasingly ...,"[Gene Expression Profiling, Humans, Immunoglob...","[{'name': 'W.J. Chng', 'org': 'Mayo Clinic Ari...",{'name': 'Best practice & research. Clinical h...,10.1016/j.beha.2007.08.004,18
3,16365419,"[20498830, 26334995]",2006-01-01,PU 1 regulates cathepsin S expression in profe...,"Journal of immunology (Baltimore, Md. : 1950)",Cathepsin S (CTSS) is a cysteine protease that...,"[Animals, Antigen-Presenting Cells, immunology...","[{'name': 'Ying Wang', 'id': '53f5626bdabfae5d...","{'name': 'Journal of immunology (Baltimore, Md...",10.4049/jimmunol.176.1.275,2
4,17251694,"[25793766, 26843986, 26977594, 31150452]",2007-02-01,Falls and gait characteristics among older per...,American journal of physical medicine & rehabi...,To prospectively determine the frequency and c...,"[Accidental Falls, Age Factors, Aged, Biomecha...","[{'name': 'Trina K. DeMott', 'org': 'Departmen...",{'name': 'American journal of physical medicin...,10.1097/PHM.0b013e31802ee1d1,4

**Reformat journal column**



*   Remove periods and spaces at the end of the string
*   Remove extra spaces after colons

In [225]:
train_ds['journal'].unique()

array(['The Journal of infectious diseases',
       'The Journal of infectious diseases.',
       'Best practice & research. Clinical haematology', ...,
       'Comprehensive psychiatry. ', 'Immunological reviews.',
       'Journal of vascular surgery :  official publication, the Society for Vascular Surgery [and] International Society for Cardiovascular Surgery, North American Chapter. '],
      dtype=object)

In [229]:
journals = []

for i in range(len(train_ds)):
  journals.append(train_ds['journal'][i].rstrip(". "))
  if ":  " in journals[i]:
    journals[i] = journals[i].replace(":  ", ": ")

train_ds['journal'] = journals

In [230]:
arr = train_ds['journal'].unique()
arr.sort()
for a in arr:
  print(a)

AACN advanced critical care
AAOHN journal : official journal of the American Association of Occupational Health Nurses
ACS chemical biology
ACS chemical neuroscience
ACS nano
AIDS (London, England)
AIDS and behavior
AIDS care
AIDS education and prevention : official publication of the International Society for AIDS Education
AIDS patient care and STDs
AIDS research and human retroviruses
AIHAJ : a journal for the science of occupational and environmental health and safety
AJNR. American journal of neuroradiology
AJR. American journal of roentgenology
ANS. Advances in nursing science
ASAIO journal (American Society for Artificial Internal Organs : 1992)
ASN neuro
Abdominal imaging
Academic emergency medicine : official journal of the Society for Academic Emergency Medicine
Academic medicine : journal of the Association of American Medical Colleges
Academic pediatrics
Academic psychiatry : the journal of the American Association of Directors of Psychiatric Residency Training and the Association for Academic Psychiatry
Academic radiology
Accident; analysis and prevention
Accountability in research
Accounts of chemical research
Acta anatomica
Acta astronautica
Acta biochimica et biophysica Sinica
Acta biomaterialia
Acta crystallographica. Section D, Biological crystallography
Acta crystallographica. Section F, Structural biology and crystallization communications
Acta diabetologica
Acta endocrinologica
Acta haematologica
Acta neurochirurgica. Supplement
Acta neurologica Scandinavica
Acta neuropathologica
Acta neuropathologica communications
Acta obstetricia et gynecologica Scandinavica
Acta oto-laryngologica
Acta paediatrica (Oslo, Norway : 1992)
Acta paediatrica (Oslo, Norway : 1992). Supplement
Acta pharmacologica Sinica
Acta physiologica (Oxford, England)
Acta physiologica Scandinavica
Acta psychiatrica Scandinavica
Acta psychiatrica Scandinavica. Supplementum
Acta tropica
Acupuncture in medicine : journal of the British Medical Acupuncture Society
Addiction (Abingdon, England)
Addiction biology
Addictive behaviors
Administration and policy in mental health
Advanced drug delivery reviews
Advanced healthcare materials
Advances in anatomic pathology
Advances in chronic kidney disease
Advances in dental research
Advances in dermatology
Advances in enzyme regulation
Advances in experimental medicine and biology
Advances in health sciences education : theory and practice
Advances in nutrition (Bethesda, Md.)
Advances in pediatrics
Advances in pharmacology (San Diego, Calif.)
Advances in physiology education
Advances in psychosomatic medicine
Advances in renal replacement therapy
Advances in therapy
African health sciences
African journal of psychiatry
Age (Dordrecht, Netherlands)
Age and ageing
Ageing research reviews
Aggressive behavior
Aging & mental health
Aging cell
Aging clinical and experimental research
Alcohol (Fayetteville, N.Y.)
Alcohol and alcoholism (Oxford, Oxfordshire)
Alcoholism, clinical and experimental research
Alimentary pharmacology & therapeutics
Allergy
Allergy and asthma proceedings
Alzheimer disease and associated disorders
Alzheimer's & dementia : the journal of the Alzheimer's Association
Ambulatory pediatrics : the official journal of the Ambulatory Pediatric Association
American Indian and Alaska native mental health research (Online)
American Society of Clinical Oncology educational book. American Society of Clinical Oncology. Annual Meeting
American heart journal
American journal of Alzheimer's disease and other dementias
American journal of audiology
American journal of cardiovascular drugs : drugs, devices, and other interventions
American journal of clinical dermatology
American journal of clinical oncology
American journal of clinical pathology
American journal of community psychology
American journal of critical care : an official publication, American Association of Critical-Care Nurses
American journal of disaster medicine
American journal of diseases of children (1960)
American journal of epidemiology
American journal of health behavior
American journal of health promotion : AJHP
American journal of health-system pharmacy : AJHP : official journal of the American Society of Health-System Pharmacists
American journal of hematology
American journal of human biology : the official journal of the Human Biology Council
American journal of human genetics
American journal of hypertension
American journal of industrial medicine
American journal of infection control
American journal of kidney diseases : the official journal of the National Kidney Foundation
American journal of medical genetics
American journal of medical genetics. Part A
American journal of medical genetics. Part B, Neuropsychiatric genetics : the official publication of the International Society of Psychiatric Genetics
American journal of medical genetics. Part C, Seminars in medical genetics
American journal of medical genetics. Supplement
American journal of medical quality : the official journal of the American College of Medical Quality
American journal of men's health
American journal of mental retardation : AJMR
American journal of nephrology
American journal of obstetrics and gynecology
American journal of ophthalmology
American journal of orthodontics and dentofacial orthopedics : official publication of the American Association of Orthodontists, its constituent societies, and the American Board of Orthodontics
American journal of otolaryngology
American journal of perinatology
American journal of pharmaceutical education
American journal of physical medicine & rehabilitation
American journal of physiology. Cell physiology
American journal of physiology. Endocrinology and metabolism
American journal of physiology. Gastrointestinal and liver physiology
American journal of physiology. Heart and circulatory physiology
American journal of physiology. Lung cellular and molecular physiology
American journal of physiology. Regulatory, integrative and comparative physiology
American journal of physiology. Renal physiology
American journal of preventive medicine
American journal of primatology
American journal of psychotherapy
American journal of public health
American journal of reproductive immunology (New York, N.Y. : 1989)
American journal of respiratory and critical care medicine
American journal of respiratory cell and molecular biology
American journal of rhinology & allergy
American journal of surgery
American journal of therapeutics
American journal of transplantation : official journal of the American Society of Transplantation and the American Society of Transplant Surgeons
American journal of veterinary research
American sociological review
Amino acids
Amyloid : the international journal of experimental and clinical investigation : the official journal of the International Society of Amyloidosis
Amyotrophic lateral sclerosis & frontotemporal degeneration
Anadolu kardiyoloji dergisi : AKD = the Anatolian journal of cardiology
Anaerobe
Analytical biochemistry
Analytical chemistry
Anatomical record (Hoboken, N.J. : 2007)
Anatomical science international
Anesthesia and analgesia
Anesthesiology
Anesthesiology clinics
Angewandte Chemie (International ed. in English)
Angiogenesis
Animal behaviour
Animal cognition
Animal genetics
Animal reproduction science
Annals of allergy, asthma & immunology : official publication of the American College of Allergy, Asthma, & Immunology
Annals of behavioral medicine : a publication of the Society of Behavioral Medicine
Annals of biomedical engineering
Annals of clinical psychiatry : official journal of the American Academy of Clinical Psychiatrists
Annals of diagnostic pathology
Annals of dyslexia
Annals of emergency medicine
Annals of epidemiology
Annals of family medicine
Annals of human biology
Annals of human genetics
Annals of internal medicine
Annals of medicine
Annals of neurology
Annals of nutrition & metabolism
Annals of oncology : official journal of the European Society for Medical Oncology
Annals of oncology : official journal of the European Society for Medical Oncology / ESMO
Annals of plastic surgery
Annals of surgery
Annals of surgical oncology
Annals of the American Thoracic Society
Annals of the New York Academy of Sciences
Annals of the rheumatic diseases
Annals of tropical medicine and parasitology
Annals of vascular surgery
Annual review of biochemistry
Annual review of biophysics
Annual review of cell and developmental biology
Annual review of clinical psychology
Annual review of entomology
Annual review of genomics and human genetics
Annual review of immunology
Annual review of medicine
Annual review of microbiology
Annual review of neuroscience
Annual review of nutrition
Annual review of pathology
Annual review of pharmacology and toxicology
Annual review of physiology
Annual review of psychology
Annual review of public health
Anti-cancer agents in medicinal chemistry
Anti-cancer drugs
Antimicrobial agents and chemotherapy
Antioxidants & redox signaling
Antiviral research
Antiviral therapy
Anxiety, stress, and coping
Apoptosis : an international journal on programmed cell death
Appetite
Applied and environmental microbiology
Applied biochemistry and biotechnology
Applied clinical informatics
Applied ergonomics
Applied health economics and health policy
Applied immunohistochemistry & molecular morphology : AIMM
Applied neuropsychology
Applied occupational and environmental hygiene
Applied optics
Applied physiology, nutrition, and metabolism = Physiologie applique?e, nutrition et me?tabolisme
Applied physiology, nutrition, and metabolism = Physiologie appliquee, nutrition et metabolisme
Applied psychophysiology and biofeedback
Applied spectroscopy
Aquatic toxicology (Amsterdam, Netherlands)
Archives italiennes de biologie
Archives of biochemistry and biophysics
Archives of clinical neuropsychology : the official journal of the National Academy of Neuropsychologists
Archives of dermatology
Archives of disease in childhood
Archives of disease in childhood. Fetal and neonatal edition
Archives of environmental & occupational health
Archives of environmental health
Archives of general psychiatry
Archives of gerontology and geriatrics
Archives of internal medicine
Archives of medical research
Archives of neurology
Archives of ophthalmology (Chicago, Ill. : 1960)
Archives of oral biology
Archives of otolaryngology--head & neck surgery
Archives of pathology & laboratory medicine
Archives of pediatrics & adolescent medicine
Archives of pharmacal research
Archives of physical medicine and rehabilitation
Archives of psychiatric nursing
Archives of sexual behavior
Archives of suicide research : official journal of the International Academy for Suicide Research
Archives of surgery (Chicago, Ill. : 1960)
Archives of virology
Archives of women's mental health
Archivum immunologiae et therapiae experimentalis
Arquivos brasileiros de endocrinologia e metabologia
Arteriosclerosis and thrombosis : a journal of vascular biology
Arteriosclerosis, thrombosis, and vascular biology
Arthritis & rheumatology (Hoboken, N.J.)
Arthritis and rheumatism
Arthritis care & research
Arthritis care and research : the official journal of the Arthritis Health Professions Association
Arthritis research
Arthritis research & therapy
Arthroscopy : the journal of arthroscopic & related surgery : official publication of the Arthroscopy Association of North America and the International Arthroscopy Association
Artificial organs
Asian Pacific journal of cancer prevention : APJCP
Asian journal of andrology
Asian journal of psychiatry
Assay and drug development technologies
Assessment
Atherosclerosis
Atherosclerosis. Supplements
Attachment & human development
Attention, perception & psychophysics
Audiology & neuro-otology
Autism : the international journal of research and practice
Autism research : official journal of the International Society for Autism Research
Autoimmunity
Autoimmunity reviews
Autonomic neuroscience : basic & clinical
Autophagy
Aviation, space, and environmental medicine
BJOG : an international journal of obstetrics and gynaecology
BJU international
BMC biochemistry
BMC bioinformatics
BMC biology
BMC biotechnology
BMC cancer
BMC cancer [electronic resource]
BMC cardiovascular disorders
BMC complementary and alternative medicine
BMC dermatology
BMC developmental biology
BMC developmental biology [electronic resource]
BMC emergency medicine
BMC evolutionary biology
BMC family practice
BMC gastroenterology
BMC genetics
BMC genomics
BMC geriatrics
BMC health services research
BMC immunology
BMC infectious diseases
BMC medical education
BMC medical education [electronic resource]
BMC medical ethics
BMC medical genetics
BMC medical genetics [electronic resource]
BMC medical genomics
BMC medical informatics and decision making
BMC medical research methodology
BMC medical research methodology [electronic resource]
BMC medicine
BMC microbiology
BMC molecular biology
BMC musculoskeletal disorders
BMC musculoskeletal disorders [electronic resource]
BMC nephrology
BMC neurology
BMC neuroscience
BMC ophthalmology
BMC oral health
BMC pediatrics
BMC pharmacology & toxicology
BMC physiology
BMC pregnancy and childbirth
BMC psychiatry
BMC public health
BMC pulmonary medicine
BMC pulmonary medicine [electronic resource]
BMC research notes
BMC systems biology
BMC veterinary research
BMJ (Clinical research ed.)
BMJ open
BMJ quality & safety
Bailliere's clinical endocrinology and metabolism
Basic & clinical pharmacology & toxicology
Basic research in cardiology
Behavior genetics
Behavior modification
Behavior research methods
Behavior therapy
Behavioral and brain functions : BBF
Behavioral medicine (Washington, D.C.)
Behavioral neuroscience
Behavioral sleep medicine
Behaviour research and therapy
Behavioural and cognitive psychotherapy
Behavioural brain research
Behavioural neurology
Behavioural pharmacology
Best practice & research. Clinical anaesthesiology
Best practice & research. Clinical endocrinology & metabolism
Best practice & research. Clinical haematology
Best practice & research. Clinical rheumatology
BioDrugs : clinical immunotherapeutics, biopharmaceuticals and gene therapy
BioEssays : news and reviews in molecular, cellular and developmental biology
BioFactors (Oxford, England)
BioMed research international
BioTechniques
Biochemical Society transactions
Biochemical and biophysical research communications
Biochemical and molecular medicine
Biochemical medicine and metabolic biology
Biochemical pharmacology
Biochemistry
Biochimica et biophysica acta
Biochimie
Bioconjugate chemistry
Biodemography and social biology
Bioelectromagnetics
Bioinformatics (Oxford, England)
Biological chemistry
Biological cybernetics
Biological psychiatry
Biological psychology
Biological research for nursing
Biological signals and receptors
Biology of blood and marrow transplantation : journal of the American Society for Blood and Marrow Transplantation
Biology of reproduction
Biology of the neonate
Biomarkers : biochemical indicators of exposure, response, and susceptibility to chemicals
Biomarkers in medicine
Biomaterials
Biomedical & environmental mass spectrometry
Biomedical chromatography : BMC
Biomedical engineering online
Biomedical microdevices
Biometals : an international journal on the role of metal ions in biology, biochemistry, and medicine
Biometrical journal. Biometrische Zeitschrift
Biometrics
Biomolecular engineering
Bioorganic & medicinal chemistry
Bioorganic & medicinal chemistry letters
Biopharmaceutics & drug disposition
Biophysical chemistry
Biophysical journal
Biosensors & bioelectronics
Biotechnology and bioengineering
Biotechnology letters
Biotechnology progress
Bipolar disorders
Birth (Berkeley, Calif.)
Birth defects research. Part A, Clinical and molecular teratology
Birth defects research. Part B, Developmental and reproductive toxicology
Blood
Blood cells, molecules & diseases
Blood pressure
Blood purification
Body image
Bone
Bone marrow transplantation
Brain & development
Brain : a journal of neurology
Brain and behavior
Brain and cognition
Brain and language
Brain connectivity
Brain imaging and behavior
Brain injury
Brain pathology (Zurich, Switzerland)
Brain research
Brain research bulletin
Brain research reviews
Brain research.  Cognitive brain research
Brain research.  Developmental brain research
Brain research.  Molecular brain research
Brain research. Brain research protocols
Brain research. Brain research reviews
Brain research. Cognitive brain research
Brain research. Developmental brain research
Brain research. Gene expression patterns
Brain research. Molecular brain research
Brain stimulation
Brain structure & function
Brain topography
Brain, behavior, and immunity
Brazilian journal of medical and biological research = Revista brasileira de pesquisas medicas e biologicas
Breast (Edinburgh, Scotland)
Breast cancer research : BCR
Breast cancer research and treatment
Breastfeeding medicine : the official journal of the Academy of Breastfeeding Medicine
Briefings in functional genomics & proteomics
British journal of anaesthesia
British journal of cancer
British journal of clinical pharmacology
British journal of haematology
British journal of health psychology
British journal of pharmacology
British journal of sports medicine
Bulletin of mathematical biology
Bulletin of the Menninger Clinic
Bulletin of the World Health Organization
Burns : journal of the International Society for Burn Injuries
CA: a cancer journal for clinicians
CMAJ : Canadian Medical Association journal = journal de l'Association medicale canadienne
CNS & neurological disorders drug targets
CNS drugs
CNS neuroscience & therapeutics
CNS spectrums
COPD
Calcified tissue international
Canadian journal of anaesthesia = Journal canadien d'anesthesie
Cancer
Cancer biology & therapy
Cancer biotherapy & radiopharmaceuticals
Cancer causes & control : CCC
Cancer cell
Cancer chemotherapy and pharmacology
Cancer detection and prevention
Cancer discovery
Cancer epidemiology, biomarkers & prevention : a publication of the American Association for Cancer Research, cosponsored by the American Society of Preventive Oncology
Cancer gene therapy
Cancer genetics
Cancer genetics and cytogenetics
Cancer immunology research
Cancer immunology, immunotherapy : CII
Cancer investigation
Cancer journal (Sudbury, Mass.)
Cancer letters
Cancer medicine
Cancer metastasis reviews
Cancer nursing
Cancer prevention research (Philadelphia, Pa.)
Cancer research
Cancer science
Cancer treatment reviews
Carbohydrate research
Carcinogenesis
Cardiology clinics
Cardiology in review
Cardiology in the young
Cardiovascular diabetology
Cardiovascular drug reviews
Cardiovascular drugs and therapy
Cardiovascular pathology : the official journal of the Society for Cardiovascular Pathology
Cardiovascular research
Cardiovascular therapeutics
Cardiovascular toxicology
Caries research
Catheterization and cardiovascular interventions : official journal of the Society for Cardiac Angiography & Interventions
Cell
Cell adhesion & migration
Cell and tissue research
Cell biochemistry and biophysics
Cell biology and toxicology
Cell biology international
Cell calcium
Cell communication & adhesion
Cell cycle (Georgetown, Tex.)
Cell death & disease
Cell death and differentiation
Cell host & microbe
Cell metabolism
Cell motility and the cytoskeleton
Cell proliferation
Cell reports
Cell research
Cell stem cell
Cell stress & chaperones
Cell structure and function
Cell transplantation
Cells, tissues, organs
Cellular & molecular immunology
Cellular and molecular life sciences : CMLS
Cellular and molecular neurobiology
Cellular immunology
Cellular microbiology
Cellular physiology and biochemistry : international journal of experimental cellular physiology, biochemistry, and pharmacology
Cellular signalling
Central nervous system agents in medicinal chemistry
Cephalalgia : an international journal of headache
Cerebellum (London, England)
Cerebral cortex (New York, N.Y. : 1991)

# 3. Download as JSONL file

##3.1 Convert to JSONL

In [231]:
train_ds.to_json('train_data.jsonl', orient='records', lines=True)

##3.2 Download

In [232]:
from google.colab import files
files.download('train_data.jsonl')

In [235]:
!git checkout cleaning

* cleaning
  main

In [236]:
!git pull origin main

From https://github.com/kkartsen/NLP_Hidden-Gems_Final-Project
 * branch            main       -> FETCH_HEAD
Updating a8dc675..846e790
Fast-forward
 train.txt.zip.002 | Bin 0 -> 8573319 bytes
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 train.txt.zip.002

In [252]:
!git add 'train_data.jsonl'

In [244]:
!git config --global user.email "kfkartsen@wpi.edu"

In [253]:
!git commit -m "cleaned and formatted training data"

On branch cleaning
Your branch is ahead of 'origin/cleaning' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

In [254]:
!git push https://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@github.com/kkartsen/NLP_Hidden-Gems_Final-Project.git

Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
error: RPC failed; HTTP 408 curl 22 The requested URL returned error: 408
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (5/5), 79.06 MiB | 3.57 MiB/s, done.
Total 5 (delta 1), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date